[package]
name = "hexchat_api"
version = "0.1.0"
authors = ["ttappr <tmtappr@gmail.com>"]
edition = "2018"

[lib]
name = "hexchat_api"
#crate-type = ["cdylib"]

[dependencies]
libc = "0.2.84"
backtrace = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

